
services:
  postgres:
    image: "postgres:17.5-alpine"
    container_name: lab3_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab3_backend
    env_file:
      - ./backend/cmd/.env
      - ./backend/cmd/boot.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8000/web/products || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: lab3_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/web/products. || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  migrate:
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.24-alpine
        WORKDIR /app
        COPY . .
        RUN go mod download
        CMD ["go", "run", "./backend/cmd/migrate/main.go"]
    container_name: lab3_migrate
    env_file:
      - ./backend/cmd/boot.env
    depends_on:
      postgres:
        condition: service_healthy

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: lab3_centrifugo
    ports:
      - "8001:8000"
    command: centrifugo --config /etc/centrifugo/config.json
    volumes:
      - ./centrifugo_config.json:/etc/centrifugo/config.json
    environment:
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=my_secret_key
      - CENTRIFUGO_ADMIN_PASSWORD=admin
      - CENTRIFUGO_ADMIN_SECRET=admin
      - CENTRIFUGO_API_KEY=my_api_key

volumes:
  postgres_data:
